# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frame_login(object):
    def setupUi(self, frame_login):
        frame_login.setObjectName("frame_login")
        frame_login.resize(373, 364)
        frame_login.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"background-color: qlineargradient(spread:pad, x1:0.17, y1:0.210227, x2:1, y2:1, stop:0.170455 rgba(65, 150, 173, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(frame_login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 50, 101, 21))
        self.label.setStyleSheet("background-color: rga(0,0,0,0%);\n"
"font: 87 14pt \"Arial\";\n"
"border: None")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 130, 111, 21))
        self.label_2.setStyleSheet("background-color: rga(0,0,0,0%);\n"
"font: 87 14pt \"Arial\";\n"
"border: None")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.usuarios = QtWidgets.QLineEdit(self.centralwidget)
        self.usuarios.setGeometry(QtCore.QRect(90, 80, 201, 20))
        self.usuarios.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: None;\n"
"")
        self.usuarios.setAlignment(QtCore.Qt.AlignCenter)
        self.usuarios.setObjectName("usuarios")
        self.contrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.contrasena.setGeometry(QtCore.QRect(90, 160, 201, 20))
        self.contrasena.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: None;\n"
"")
        self.contrasena.setAlignment(QtCore.Qt.AlignCenter)
        self.contrasena.setObjectName("contrasena")
        self.Ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.Ingresar.setGeometry(QtCore.QRect(150, 210, 81, 41))
        self.Ingresar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 85, 255);\n"
"    \n"
"    font: 75 8pt \"Arial\";\n"
"border-radius: 10px;\n"
"border: 3px solid #000000;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 170, 127);\n"
"    \n"
"    font: 75 8pt \"Arial\";\n"
"border-radius: 10px;\n"
"border: 3px solid #ffffff;\n"
"}\n"
"\n"
"")
        self.Ingresar.setObjectName("Ingresar")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 270, 181, 16))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 25px;\n"
"border: 1px solid#00007f;\n"
"}\n"
"QProgressBar::Chunk{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.29, y1:0.704545, x2:1, y2:1, stop:0 rgba(43, 146, 106, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-radius: 25px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.salir = QtWidgets.QPushButton(self.centralwidget)
        self.salir.setGeometry(QtCore.QRect(270, 300, 71, 31))
        self.salir.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0,0%);\n"
"    \n"
"    font: 75 8pt \"Arial\";\n"
"border-radius: 10px;\n"
"border: 1px solid #000000;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 170, 127);\n"
"    \n"
"    font: 75 8pt \"Arial\";\n"
"border-radius: 10px;\n"
"border: 3px solid #ffffff;\n"
"}\n"
"\n"
"")
        self.salir.setObjectName("salir")
        self.clave_incorrecta = QtWidgets.QLabel(self.centralwidget)
        self.clave_incorrecta.setGeometry(QtCore.QRect(110, 190, 151, 16))
        self.clave_incorrecta.setStyleSheet("background-color: rga(0,0,0,0%);\n"
"font: 87 8pt \"Arial\";\n"
"color: rgb(170, 0, 0);\n"
"border: None")
        self.clave_incorrecta.setText("")
        self.clave_incorrecta.setAlignment(QtCore.Qt.AlignCenter)
        self.clave_incorrecta.setObjectName("clave_incorrecta")
        self.usuario_incorrecto = QtWidgets.QLabel(self.centralwidget)
        self.usuario_incorrecto.setGeometry(QtCore.QRect(110, 110, 151, 16))
        self.usuario_incorrecto.setStyleSheet("background-color: rga(0,0,0,0%);\n"
"font: 87 8pt \"Arial\";\n"
"color: rgb(170, 0, 0);\n"
"border: None")
        self.usuario_incorrecto.setText("")
        self.usuario_incorrecto.setAlignment(QtCore.Qt.AlignCenter)
        self.usuario_incorrecto.setObjectName("usuario_incorrecto")
        self.cargando = QtWidgets.QLabel(self.centralwidget)
        self.cargando.setGeometry(QtCore.QRect(110, 300, 151, 16))
        self.cargando.setStyleSheet("background-color: rga(0,0,0,0%);\n"
"font: 87 8pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"border: None")
        self.cargando.setText("")
        self.cargando.setAlignment(QtCore.Qt.AlignCenter)
        self.cargando.setObjectName("cargando")
        frame_login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(frame_login)
        self.statusbar.setObjectName("statusbar")
        frame_login.setStatusBar(self.statusbar)

        self.retranslateUi(frame_login)
        QtCore.QMetaObject.connectSlotsByName(frame_login)

    def retranslateUi(self, frame_login):
        _translate = QtCore.QCoreApplication.translate
        frame_login.setWindowTitle(_translate("frame_login", "MainWindow"))
        self.label.setText(_translate("frame_login", "Usuario"))
        self.label_2.setText(_translate("frame_login", "Clave"))
        self.usuarios.setPlaceholderText(_translate("frame_login", "Ingrese su correo"))
        self.contrasena.setPlaceholderText(_translate("frame_login", "Ingrese su contraseña"))
        self.Ingresar.setText(_translate("frame_login", "Iniciar sesión"))
        self.salir.setText(_translate("frame_login", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frame_login = QtWidgets.QMainWindow()
    ui = Ui_frame_login()
    ui.setupUi(frame_login)
    frame_login.show()
    sys.exit(app.exec_())
